### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by fabreg** [redianmarku/js-twitter-bot#1]
I tried to deploy the app on Heroku but when it starts, it says:

```
7-25T11:09:31.347825+00:00 heroku[worker.1]: State changed from crashed to starting
2020-07-25T11:09:33.195188+00:00 heroku[worker.1]: Starting process with command `node src/bot.js`
2020-07-25T11:09:33.739456+00:00 heroku[worker.1]: State changed from starting to up
2020-07-25T11:09:35.133941+00:00 app[worker.1]: /app/src/bot.js:22
2020-07-25T11:09:35.133957+00:00 app[worker.1]: var retweetId = data.statuses[0].id_str;
2020-07-25T11:09:35.133958+00:00 app[worker.1]: ^
2020-07-25T11:09:35.133959+00:00 app[worker.1]:
2020-07-25T11:09:35.133959+00:00 app[worker.1]: TypeError: Cannot read property 'id_str' of undefined
2020-07-25T11:09:35.133960+00:00 app[worker.1]: at /app/src/bot.js:22:46
2020-07-25T11:09:35.133960+00:00 app[worker.1]: at /app/node_modules/twit/lib/twitter.js:127:13
2020-07-25T11:09:35.133961+00:00 app[worker.1]: at onRequestComplete (/app/node_modules/twit/lib/twitter.js:352:5)
2020-07-25T11:09:35.133961+00:00 app[worker.1]: at Request.<anonymous> (/app/node_modules/twit/lib/twitter.js:364:7)
2020-07-25T11:09:35.133962+00:00 app[worker.1]: at Request.emit (events.js:327:22)
2020-07-25T11:09:35.133962+00:00 app[worker.1]: at Gunzip.<anonymous> (/app/node_modules/request/request.js:1076:12)
2020-07-25T11:09:35.133962+00:00 app[worker.1]: at Object.onceWrapper (events.js:421:28)
2020-07-25T11:09:35.133963+00:00 app[worker.1]: at Gunzip.emit (events.js:327:22)
2020-07-25T11:09:35.133963+00:00 app[worker.1]: at endReadableNT (_stream_readable.js:1220:12)
2020-07-25T11:09:35.133964+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-07-25T11:09:35.182450+00:00 heroku[worker.1]: Process exited with status 1
2020-07-25T11:09:35.214804+00:00 heroku[worker.1]: State changed from up to crashed
```

Any idea why?

**Comment by fabreg** [comment]
Found and fixed in #2 
Feel freed to add it - Thank you.
